kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: xty
  version: alpha
spec:
  request:
    - method: GET
      resource: /pet/1
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: ""
  api:
    $ref: dev:APIRouting:1.0
